name: MSCIS Daily
on:
  schedule:
    - cron: "0 6 * * *"  # 06:00 UTC daily
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Fetch RSS (demo)
        run: python src/mscistk/ingest/rss_ingest.py src/mscistk/config/settings.example.yaml > out/rss.json
      - name: Render demo newsletter
        run: python src/mscistk/generate/render.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mscis-output
          path: out/**
